# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/etien/Desktop/Proyecto-2-SEP-G14/Top/Top/Top.srcs/sources_1/bd/top/ip/top_rst_ps7_0_50M_0/top_rst_ps7_0_50M_0.xci
# IP: The module: 'top_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/etien/Desktop/Proyecto-2-SEP-G14/Top/Top/Top.srcs/sources_1/bd/top/ip/top_rst_ps7_0_50M_0/top_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/etien/Desktop/Proyecto-2-SEP-G14/Top/Top/Top.srcs/sources_1/bd/top/ip/top_rst_ps7_0_50M_0/top_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/etien/Desktop/Proyecto-2-SEP-G14/Top/Top/Top.srcs/sources_1/bd/top/ip/top_rst_ps7_0_50M_0/top_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/etien/Desktop/Proyecto-2-SEP-G14/Top/Top/Top.srcs/sources_1/bd/top/ip/top_rst_ps7_0_50M_0/top_rst_ps7_0_50M_0.xci
# IP: The module: 'top_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/etien/Desktop/Proyecto-2-SEP-G14/Top/Top/Top.srcs/sources_1/bd/top/ip/top_rst_ps7_0_50M_0/top_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/etien/Desktop/Proyecto-2-SEP-G14/Top/Top/Top.srcs/sources_1/bd/top/ip/top_rst_ps7_0_50M_0/top_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/etien/Desktop/Proyecto-2-SEP-G14/Top/Top/Top.srcs/sources_1/bd/top/ip/top_rst_ps7_0_50M_0/top_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
