# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/etien/Desktop/Proyecto-2-SEP-G14/Oficial/Zybo-Z7-Master.xdc

# Block Designs: bd/uart/uart.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart || ORIG_REF_NAME==uart} -quiet] -quiet

# IP: bd/uart/ip/uart_processing_system7_0_0/uart_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_processing_system7_0_0 || ORIG_REF_NAME==uart_processing_system7_0_0} -quiet] -quiet

# IP: bd/uart/ip/uart_vio_0_0/uart_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_vio_0_0 || ORIG_REF_NAME==uart_vio_0_0} -quiet] -quiet

# IP: bd/uart/ip/uart_ps7_0_axi_periph_0/uart_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_ps7_0_axi_periph_0 || ORIG_REF_NAME==uart_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/uart/ip/uart_rst_ps7_0_50M_0/uart_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_rst_ps7_0_50M_0 || ORIG_REF_NAME==uart_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/uart/ip/uart_circular_buffer_0_0/uart_circular_buffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_circular_buffer_0_0 || ORIG_REF_NAME==uart_circular_buffer_0_0} -quiet] -quiet

# IP: bd/uart/ip/uart_FFT_0_0/uart_FFT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_FFT_0_0 || ORIG_REF_NAME==uart_FFT_0_0} -quiet] -quiet

# IP: bd/uart/ip/uart_blk_mem_gen_0_0/uart_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_blk_mem_gen_0_0 || ORIG_REF_NAME==uart_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/uart/ip/uart_xlslice_0_0/uart_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_xlslice_0_0 || ORIG_REF_NAME==uart_xlslice_0_0} -quiet] -quiet

# IP: bd/uart/ip/uart_xlslice_0_1/uart_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_xlslice_0_1 || ORIG_REF_NAME==uart_xlslice_0_1} -quiet] -quiet

# IP: bd/uart/ip/uart_AXIFloat_1_0/uart_AXIFloat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_AXIFloat_1_0 || ORIG_REF_NAME==uart_AXIFloat_1_0} -quiet] -quiet

# IP: bd/uart/ip/uart_clk_wiz_0_0/uart_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_clk_wiz_0_0 || ORIG_REF_NAME==uart_clk_wiz_0_0} -quiet] -quiet

# IP: bd/uart/ip/uart_auto_pc_0/uart_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_auto_pc_0 || ORIG_REF_NAME==uart_auto_pc_0} -quiet] -quiet

# XDC: bd/uart/uart_ooc.xdc
