webtalk_init -webtalk_dir C:/Users/Amteo/Desktop/Universidad/SEP/Proyecto1/CircularBuffer/CircularBuffer.sim/sim_1/behav/xsim/xsim.dir/circular_buffer_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri May 10 20:08:26 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0afeec6d-16ee-4da5-bf50-e3ff505271bc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fe5484408b2d48fc924090328d817f71" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "58" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "52603545 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.14_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15372_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3121436436 -regid "" -xml C:/Users/Amteo/Desktop/Universidad/SEP/Proyecto1/CircularBuffer/CircularBuffer.sim/sim_1/behav/xsim/xsim.dir/circular_buffer_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Amteo/Desktop/Universidad/SEP/Proyecto1/CircularBuffer/CircularBuffer.sim/sim_1/behav/xsim/xsim.dir/circular_buffer_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Amteo/Desktop/Universidad/SEP/Proyecto1/CircularBuffer/CircularBuffer.sim/sim_1/behav/xsim/xsim.dir/circular_buffer_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
