# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/test_sd/test_sd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_sd || ORIG_REF_NAME==test_sd} -quiet] -quiet

# IP: bd/test_sd/ip/test_sd_processing_system7_0_0/test_sd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_sd_processing_system7_0_0 || ORIG_REF_NAME==test_sd_processing_system7_0_0} -quiet] -quiet

# XDC: bd/test_sd/test_sd_ooc.xdc
