# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/etien/Desktop/Proyecto-2-SEP-G14/Of/Zybo-Z7-Master.xdc

# Block Designs: bd/DEMO/DEMO.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO || ORIG_REF_NAME==DEMO} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_quad_spi_0_0/DEMO_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_quad_spi_0_0 || ORIG_REF_NAME==DEMO_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_processing_system7_0_0/DEMO_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_processing_system7_0_0 || ORIG_REF_NAME==DEMO_processing_system7_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_gpio_0_0/DEMO_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_gpio_0_0 || ORIG_REF_NAME==DEMO_axi_gpio_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_xbar_0/DEMO_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_xbar_0 || ORIG_REF_NAME==DEMO_xbar_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_ps7_0_axi_periph_0/DEMO_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_ps7_0_axi_periph_0 || ORIG_REF_NAME==DEMO_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_rst_ps7_0_50M_0/DEMO_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_rst_ps7_0_50M_0 || ORIG_REF_NAME==DEMO_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_quad_spi_1_0/DEMO_axi_quad_spi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_quad_spi_1_0 || ORIG_REF_NAME==DEMO_axi_quad_spi_1_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_iic_0_1/DEMO_axi_iic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_iic_0_1 || ORIG_REF_NAME==DEMO_axi_iic_0_1} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_BUZZER_0_0/DEMO_BUZZER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_BUZZER_0_0 || ORIG_REF_NAME==DEMO_BUZZER_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_gpio_0_1/DEMO_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_gpio_0_1 || ORIG_REF_NAME==DEMO_axi_gpio_0_1} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_vio_0_0/DEMO_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_vio_0_0 || ORIG_REF_NAME==DEMO_vio_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_AXIFloat_0_0/DEMO_AXIFloat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_AXIFloat_0_0 || ORIG_REF_NAME==DEMO_AXIFloat_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_timer_0_0/DEMO_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_timer_0_0 || ORIG_REF_NAME==DEMO_axi_timer_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_timer_1_0/DEMO_axi_timer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_timer_1_0 || ORIG_REF_NAME==DEMO_axi_timer_1_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_xlconcat_0_0/DEMO_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_xlconcat_0_0 || ORIG_REF_NAME==DEMO_xlconcat_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_xlslice_0_0/DEMO_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_xlslice_0_0 || ORIG_REF_NAME==DEMO_xlslice_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_xlslice_1_0/DEMO_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_xlslice_1_0 || ORIG_REF_NAME==DEMO_xlslice_1_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_circular_buffer_0_0/DEMO_circular_buffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_circular_buffer_0_0 || ORIG_REF_NAME==DEMO_circular_buffer_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_FFT_0_0/DEMO_FFT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_FFT_0_0 || ORIG_REF_NAME==DEMO_FFT_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_index_selector_0_0/DEMO_index_selector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_index_selector_0_0 || ORIG_REF_NAME==DEMO_index_selector_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_blk_mem_gen_0_0/DEMO_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_blk_mem_gen_0_0 || ORIG_REF_NAME==DEMO_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_clk_wiz_0_0/DEMO_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_clk_wiz_0_0 || ORIG_REF_NAME==DEMO_clk_wiz_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_xlslice_1_1/DEMO_xlslice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_xlslice_1_1 || ORIG_REF_NAME==DEMO_xlslice_1_1} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_xlslice_2_0/DEMO_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_xlslice_2_0 || ORIG_REF_NAME==DEMO_xlslice_2_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_xlconcat_1_0/DEMO_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_xlconcat_1_0 || ORIG_REF_NAME==DEMO_xlconcat_1_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_xlslice_4_0/DEMO_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_xlslice_4_0 || ORIG_REF_NAME==DEMO_xlslice_4_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_xlslice_4_1/DEMO_xlslice_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_xlslice_4_1 || ORIG_REF_NAME==DEMO_xlslice_4_1} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_ila_0_0/DEMO_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_ila_0_0 || ORIG_REF_NAME==DEMO_ila_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_xlslice_2_1/DEMO_xlslice_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_xlslice_2_1 || ORIG_REF_NAME==DEMO_xlslice_2_1} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_auto_pc_0/DEMO_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_auto_pc_0 || ORIG_REF_NAME==DEMO_auto_pc_0} -quiet] -quiet

# XDC: bd/DEMO/DEMO_ooc.xdc
