# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Amteo/Desktop/Universidad/SEP/Proyecto-2-SEP-G14/Tests/Zybo-Z7-Master.xdc

# Block Designs: bd/AXI_FLOAT/AXI_FLOAT.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_FLOAT || ORIG_REF_NAME==AXI_FLOAT} -quiet] -quiet

# IP: bd/AXI_FLOAT/ip/AXI_FLOAT_AXIFloat_0_0/AXI_FLOAT_AXIFloat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_FLOAT_AXIFloat_0_0 || ORIG_REF_NAME==AXI_FLOAT_AXIFloat_0_0} -quiet] -quiet

# IP: bd/AXI_FLOAT/ip/AXI_FLOAT_ila_0_0/AXI_FLOAT_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_FLOAT_ila_0_0 || ORIG_REF_NAME==AXI_FLOAT_ila_0_0} -quiet] -quiet

# IP: bd/AXI_FLOAT/ip/AXI_FLOAT_processing_system7_0_0/AXI_FLOAT_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_FLOAT_processing_system7_0_0 || ORIG_REF_NAME==AXI_FLOAT_processing_system7_0_0} -quiet] -quiet

# IP: bd/AXI_FLOAT/ip/AXI_FLOAT_vio_0_0/AXI_FLOAT_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_FLOAT_vio_0_0 || ORIG_REF_NAME==AXI_FLOAT_vio_0_0} -quiet] -quiet

# IP: bd/AXI_FLOAT/ip/AXI_FLOAT_auto_pc_0/AXI_FLOAT_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_FLOAT_auto_pc_0 || ORIG_REF_NAME==AXI_FLOAT_auto_pc_0} -quiet] -quiet

# IP: bd/AXI_FLOAT/ip/AXI_FLOAT_ps7_0_axi_periph_0/AXI_FLOAT_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_FLOAT_ps7_0_axi_periph_0 || ORIG_REF_NAME==AXI_FLOAT_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AXI_FLOAT/ip/AXI_FLOAT_rst_ps7_0_50M_0/AXI_FLOAT_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_FLOAT_rst_ps7_0_50M_0 || ORIG_REF_NAME==AXI_FLOAT_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/AXI_FLOAT/AXI_FLOAT_ooc.xdc
