# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Amteo/Desktop/Universidad/SEP/Proyecto-2-SEP-G14/Oficial/Zybo-Z7-Master.xdc

# Block Designs: bd/P2/P2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P2 || ORIG_REF_NAME==P2} -quiet] -quiet

# IP: bd/P2/ip/P2_processing_system7_0_0/P2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P2_processing_system7_0_0 || ORIG_REF_NAME==P2_processing_system7_0_0} -quiet] -quiet

# IP: bd/P2/ip/P2_axi_gpio_0_0/P2_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P2_axi_gpio_0_0 || ORIG_REF_NAME==P2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/P2/ip/P2_axi_gpio_1_0/P2_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P2_axi_gpio_1_0 || ORIG_REF_NAME==P2_axi_gpio_1_0} -quiet] -quiet

# IP: bd/P2/ip/P2_axi_quad_spi_0_0/P2_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P2_axi_quad_spi_0_0 || ORIG_REF_NAME==P2_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/P2/ip/P2_axi_quad_spi_1_0/P2_axi_quad_spi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P2_axi_quad_spi_1_0 || ORIG_REF_NAME==P2_axi_quad_spi_1_0} -quiet] -quiet

# IP: bd/P2/ip/P2_axi_iic_0_0/P2_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P2_axi_iic_0_0 || ORIG_REF_NAME==P2_axi_iic_0_0} -quiet] -quiet

# IP: bd/P2/ip/P2_xbar_0/P2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P2_xbar_0 || ORIG_REF_NAME==P2_xbar_0} -quiet] -quiet

# IP: bd/P2/ip/P2_ps7_0_axi_periph_0/P2_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P2_ps7_0_axi_periph_0 || ORIG_REF_NAME==P2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/P2/ip/P2_rst_ps7_0_50M_0/P2_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P2_rst_ps7_0_50M_0 || ORIG_REF_NAME==P2_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/P2/ip/P2_BUZZER_0_0/P2_BUZZER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P2_BUZZER_0_0 || ORIG_REF_NAME==P2_BUZZER_0_0} -quiet] -quiet

# IP: bd/P2/ip/P2_AXIFloat_0_0/P2_AXIFloat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P2_AXIFloat_0_0 || ORIG_REF_NAME==P2_AXIFloat_0_0} -quiet] -quiet

# IP: bd/P2/ip/P2_vio_0_0/P2_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P2_vio_0_0 || ORIG_REF_NAME==P2_vio_0_0} -quiet] -quiet

# IP: bd/P2/ip/P2_auto_pc_0/P2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P2_auto_pc_0 || ORIG_REF_NAME==P2_auto_pc_0} -quiet] -quiet

# IP: bd/P2/ip/P2_s00_mmu_0/P2_s00_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==P2_s00_mmu_0 || ORIG_REF_NAME==P2_s00_mmu_0} -quiet] -quiet

# XDC: bd/P2/P2_ooc.xdc
