# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Amteo/Desktop/Universidad/SEP/Proyecto-2-SEP-G14/Tests/AxiFloat/AxiFloat.srcs/sources_1/bd/AXI_FLOAT/ip/AXI_FLOAT_ila_0_0/AXI_FLOAT_ila_0_0.xci
# IP: The module: 'AXI_FLOAT_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Amteo/Desktop/Universidad/SEP/Proyecto-2-SEP-G14/Tests/AxiFloat/AxiFloat.srcs/sources_1/bd/AXI_FLOAT/ip/AXI_FLOAT_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_FLOAT_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Amteo/Desktop/Universidad/SEP/Proyecto-2-SEP-G14/Tests/AxiFloat/AxiFloat.srcs/sources_1/bd/AXI_FLOAT/ip/AXI_FLOAT_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_FLOAT_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Amteo/Desktop/Universidad/SEP/Proyecto-2-SEP-G14/Tests/AxiFloat/AxiFloat.srcs/sources_1/bd/AXI_FLOAT/ip/AXI_FLOAT_ila_0_0/AXI_FLOAT_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_FLOAT_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Amteo/Desktop/Universidad/SEP/Proyecto-2-SEP-G14/Tests/AxiFloat/AxiFloat.srcs/sources_1/bd/AXI_FLOAT/ip/AXI_FLOAT_ila_0_0/AXI_FLOAT_ila_0_0.xci
# IP: The module: 'AXI_FLOAT_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Amteo/Desktop/Universidad/SEP/Proyecto-2-SEP-G14/Tests/AxiFloat/AxiFloat.srcs/sources_1/bd/AXI_FLOAT/ip/AXI_FLOAT_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_FLOAT_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Amteo/Desktop/Universidad/SEP/Proyecto-2-SEP-G14/Tests/AxiFloat/AxiFloat.srcs/sources_1/bd/AXI_FLOAT/ip/AXI_FLOAT_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_FLOAT_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Amteo/Desktop/Universidad/SEP/Proyecto-2-SEP-G14/Tests/AxiFloat/AxiFloat.srcs/sources_1/bd/AXI_FLOAT/ip/AXI_FLOAT_ila_0_0/AXI_FLOAT_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_FLOAT_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
